all:	BestFirstSearch

BestFirstSearch:	BestFirstSearch.o
			g++  BestFirstSearch.o	-o BestFirstSearch

BestFirstSearch.o:	BestFirstSearch.cpp
			g++ -c BestFirstSearch.cpp

clean:
	rm -f *.o BestFirstSearch
